# Site settings
title: Corbin Otwell
email: cbotwell@gmail.com
url: https://cbotwell.github.io
description: "I'm currently studying Front End Engineering at The Iron Yard. Working with HTML, CSS, Sass, Handlebars, JavaScript, jQuery, Underscore, Backbone, and Ember. I like Advertising, Marketing, Antiques, Music, and Boston Terriers."
skills: "Front End Devoloper - Digital Marketing - Advertising"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Corbin Otwell
  location: Location
  social: Around the Web
  credits: Hat Tips

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/cbotwell
  - title: linkedin
    url: https://www.linkedin.com/in/corbinotwell
  - title: twitter
    url: http://twitter.com/cbotwell
  - title: instagram
    url: https://instagram.com/cbotwell/

# Postal address (add as many lines as necessary)
address:
  - line: Little Rock, Arkansas

# Credits content
credits: 'The Iron Yard, Ryan Tablada, Mary Dunlap, and <a href="http://startbootstrap.com">Freelancer Bootstrap Theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty
